apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo-staging
  namespace: flux-system
spec:
  interval: 1m
  path: ./staging/podinfo   # ✅ ubah ini jadi folder
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
