# podinfo-deployment.yml

# 0. Namespace: Membuat namespace untuk aplikasi podinfo
apiVersion: v1
kind: Namespace
metadata:
  name: podinfo-app # <-- NAMA NAMESPACE BARU
---
# 1. Deployment: Defines the desired state for your application pods.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: podinfo-app # <-- TAMBAHKAN BARIS INI
spec:
  replicas: 2
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: ghcr.io/stefanprodan/podinfo
        # {"$imagepolicy": "flux-system:podinfo"}
        ports:
        - containerPort: 9898
---
# 2. Service: Creates a stable network endpoint to access the pods.
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: podinfo-app # <-- TAMBAHKAN BARIS INI
spec:
  selector:
    app: podinfo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9898
---
# 3. Route: Exposes the Service with a public URL (OpenShift specific).
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: podinfo
  namespace: podinfo-app # <-- TAMBAHKAN BARIS INI
spec:
  to:
    kind: Service
    name: podinfo
  port:
    targetPort: 80
