# podinfo-deployment.yml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: ghcr.io/stefanprodan/podinfo # <-- HAPUS TAG VERSI DI SINI
        # {"$imagepolicy": "flux-system:podinfo"} # <-- TAMBAHKAN BARIS KOMENTAR INI
        ports:
        - containerPort: 9898

---

apiVersion: v1
kind: Service
metadata:
  name: podinfo
spec:
  selector:
    app: podinfo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9898

---

apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: podinfo
spec:
  to:
    kind: Service
    name: podinfo
  port:
    targetPort: 80
